--- #YAML:1.0
name:               xcruciate
version:            0.18
abstract:           Libraries for perl scripts in and around the Xcruciate server project
author:
    - Mark Howe <melonman@cpan.org>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::LibXML:	0
    XML::LibXSLT:	0
resources:
    repository:	     svn://xcruciate.co.uk/cpan
no_index:
    directory:
        - t
generated_by:       The old-fashioned keystrokes of Melonman
